database-path: ${DB_PATH:${user.home}/.quote-generator/db}

quarkus:
  datasource:
    db-kind: sqlite
    jdbc:
      url: jdbc:sqlite:${database-path}/tasks.db?journal_mode=WAL&busy_timeout=1&synchronous=NORMAL
      min-size: 1
      max-size: 1
      initial-size: 1
      acquisition-timeout: 30s
      leak-detection-interval: 10s
      idle-removal-interval: 5m
      background-validation-interval: 30s
  hibernate-orm:
    dialect: org.hibernate.community.dialect.SQLiteDialect
    log:
      sql: true
      format-sql: true
  liquibase:
    migrate-at-start: true
    change-log: db/changelog/db.changelog-master.yaml
    contexts: all
    validate-on-migrate: true
  log:
    level: INFO
    category:
      "com.goat":
        level: DEBUG