package com.goat.infrastructure.config.energyoperator.bra

import com.goat.infrastructure.config.energyoperator.EnergyOperator
import com.goat.infrastructure.extensions.Locales
import java.util.Locale

enum class BrazilianEnergyOperator(
    override val operatorName: String,
    override val country: Locale = Locales.BRAZIL
) : EnergyOperator {
    NEOENERGIA_BRASILIA("Neoenergia Brasília"),
    LIGHT_SESA("LIGHT SESA"),
    ELETROCAR("ELETROCAR"),
    CERNHE("CERNHE"),
    EQUATORIAL_MA("EQUATORIAL MA"),
    EQUATORIAL_GO("EQUATORIAL GO"),
    CEREJ("CEREJ"),
    CERAL_DIS("CERAL-DIS"),
    COOPERCOCAL("COOPERCOCAL"),
    CERSUL("CERSUL"),
    CERCOS("CERCOS"),
    COOPERZEM("COOPERZEM"),
    SULGIPE("SULGIPE"),
    DMED("DMED"),
    ENEL_RJ("ENEL RJ"),
    CERGAPA("CERGAPA"),
    EAC("EAC"),
    CERILUZ("CERILUZ"),
    CEPRAG("CEPRAG"),
    CERVAM("CERVAM"),
    CELETRO("CELETRO"),
    ESE("ESE"),
    CERRP("CERRP"),
    CERTAJA("CERTAJA"),
    CRELUZ_D("CRELUZ-D"),
    ENEL_CE("ENEL CE"),
    CERMISSOES("CERMISSÕES"),
    ELEKTRO("ELEKTRO"),
    COORSEL("COORSEL"),
    RGE("RGE"),
    ESS("ESS"),
    CASTRO_DIS("CASTRO-DIS"),
    CEDRAP("CEDRAP"),
    CELESC("CELESC"),
    COSERN("COSERN"),
    COOPERNORTE("COOPERNORTE"),
    EDP_SP("EDP SP"),
    COPREL("COPREL"),
    CEMIG_D("CEMIG-D"),
    CPFL_PIRATINING("CPFL-PIRATINING"),
    MUXENERGIA("MUXENERGIA"),
    EDP_ES("EDP ES"),
    CERAL_ARARUAMA("CERAL ARARUAMA"),
    NEOENERGIA_PE("Neoenergia PE"),
    COOPERMILA("COOPERMILA"),
    CERMOFUL("CERMOFUL"),
    COELBA("COELBA"),
    CERAL_ANITAPOLIS("CERAL ANITÁPOLIS"),
    UHENPAL("UHENPAL"),
    CERIS("CERIS"),
    CERCI("CERCI"),
    EFLJC("EFLJC"),
    CPFL_PAULISTA("CPFL-PAULISTA"),
    COOPERALIANC("COOPERALIANÇA"),
    CERTHIL("CERTHIL"),
    ELETROPAULO("ELETROPAULO"),
    CETRIL("CETRIL"),
    ERO("ERO"),
    COOPERLUZ("COOPERLUZ"),
    CPFL_SANTA_CRUZ("CPFL Santa Cruz"),
    EQUATORIAL_PA("EQUATORIAL PA"),
    CERMC("CERMC"),
    CERIPA("CERIPa"),
    HIDROPAN("HIDROPAN"),
    CERTREL("CERTREL"),
    CERGRAL("CERGRAL"),
    EQUATORIAL_AL("EQUATORIAL AL"),
    EPB("EPB"),
    CEGERO("CEGERO"),
    ELFSM("ELFSM"),
    CERPRO("CERPRO"),
    BOA_VISTA("BOA VISTA"),
    CEDRI("CEDRI"),
    COOPERA("COOPERA"),
    EMT("EMT"),
    CERFOX("CERFOX"),
    ETO("ETO"),
    DEMEI("DEMEI"),
    CERSAD_DISTRIBUI("CERSAD DISTRIBUI"),
    CERGAL("CERGAL"),
    CERTEL_ENERGIA("CERTEL ENERGIA"),
    CEA("CEA"),
    EFLUL("EFLUL"),
    COCEL("COCEL"),
    CERBRANORTE("CERBRANORTE"),
    CEJAMA("CEJAMA"),
    EMS("EMS"),
    CERPALO("CERPALO"),
    CEEE_D("CEEE-D"),
    CHESP("CHESP"),
    CERES("CERES"),
    CEMIRIM("CEMIRIM"),
    AME("AME"),
    CERACA("Ceraçá"),
    PACTO_ENERGIA_PR("PACTO ENERGIA PR"),
    EMR("EMR"),
    COPEL_DIS("COPEL-DIS"),
    DCELT("DCELT"),
    CODESAM("CODESAM"),
    EQUATORIAL_PI("EQUATORIAL PI"),
    CERIM("CERIM"),
    COOPERSUL("COOPERSUL");

    companion object {
        fun fromOperatorName(operatorName: String): BrazilianEnergyOperator =
            entries.firstOrNull { it.operatorName == operatorName }
                ?: throw IllegalArgumentException("Unknown energy operator: $operatorName")
    }
}